name: esc_pos_utils_plus
description: Basic Flutter/Dart classes for ESC/POS printing. Ticket class generates ESC/POS commands that can be sent to a thermal printer.
version: 2.0.2
homepage: https://github.com/andrey-ushakov/esc_pos_utils

environment:
  sdk: '>=2.16.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  image: ^4.0.17
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/esc_pos_utils_plus/resources/capabilities.json
